name: Derp
version: 0.1
description: Derping it up
author: Jaiimc
main: com.github.Jaiimc.Derp.Derp
commands:
    derp:
        description: Derp messages.
        permission: Derp.derp
    derpage:
        description: Derp messages.
        permission: Derp.derpage